{
 "title": "Davis",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Payloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Station 0 Payloads",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "measurement": "TEST",
       "select": [
        [
         { "params": [ "Payload" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "ID::field", "operator": "=", "value": "0" }
       ]
      }
     ]
    },
    {
     "title": "Station 1 Payloads",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "measurement": "TEST",
       "select": [
        [
         { "params": [ "Payload" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "ID::field", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "Station 2 Payloads",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "measurement": "TEST",
       "select": [
        [
         { "params": [ "Payload" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "ID::field", "operator": "=", "value": "2" }
       ]
      }
     ]
    },
    {
     "title": "Station 3 Payloads",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "measurement": "TEST",
       "select": [
        [
         { "params": [ "Payload" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "ID::field", "operator": "=", "value": "3" }
       ]
      }
     ]
    },
    {
     "title": "Station 4 Payloads",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "measurement": "TEST",
       "select": [
        [
         { "params": [ "Payload" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "ID::field", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "Station 5 Payloads",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "measurement": "TEST",
       "select": [
        [
         { "params": [ "Payload" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "ID::field", "operator": "=", "value": "5" }
       ]
      }
     ]
    },
    {
     "title": "Station 6 Payloads",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "measurement": "TEST",
       "select": [
        [
         { "params": [ "Payload" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "ID::field", "operator": "=", "value": "6" }
       ]
      }
     ]
    },
    {
     "title": "Station 7 Payloads",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "measurement": "TEST",
       "select": [
        [
         { "params": [ "Payload" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "ID::field", "operator": "=", "value": "7" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Status Map",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "query": "SELECT \"Battery\", \"Latitude\", \"Longitude\" FROM \"TEST\" WHERE (\"ID\"::field = '0') AND $timeFilter",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PacketCount" ], "type": "alias" }
      ],
      [
       { "params": [ "Latitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Latitude" ], "type": "alias" }
      ],
      [
       { "params": [ "Longitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Longitude" ], "type": "alias" }
      ],
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Battery" ], "type": "alias" }
      ],
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Humidity" ], "type": "alias" }
      ],
      [
       { "params": [ "Rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rain" ], "type": "alias" }
      ],
      [
       { "params": [ "SolarRadiation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Solar Radiation" ], "type": "alias" }
      ],
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "UV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "UV" ], "type": "alias" }
      ],
      [
       { "params": [ "WindDir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wind Direction" ], "type": "alias" }
      ],
      [
       { "params": [ "WindSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wind Speed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "query": "SELECT \"Battery\", \"Latitude\", \"Longitude\" FROM \"TEST\" WHERE (\"ID\"::field = '0') AND $timeFilter",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PacketCount" ], "type": "alias" }
      ],
      [
       { "params": [ "Latitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Latitude" ], "type": "alias" }
      ],
      [
       { "params": [ "Longitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Longitude" ], "type": "alias" }
      ],
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Battery" ], "type": "alias" }
      ],
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Humidity" ], "type": "alias" }
      ],
      [
       { "params": [ "Rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rain" ], "type": "alias" }
      ],
      [
       { "params": [ "SolarRadiation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Solar Radiation" ], "type": "alias" }
      ],
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "UV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "UV" ], "type": "alias" }
      ],
      [
       { "params": [ "WindDir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wind Direction" ], "type": "alias" }
      ],
      [
       { "params": [ "WindSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wind Speed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "query": "SELECT \"Battery\", \"Latitude\", \"Longitude\" FROM \"TEST\" WHERE (\"ID\"::field = '0') AND $timeFilter",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PacketCount" ], "type": "alias" }
      ],
      [
       { "params": [ "Latitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Latitude" ], "type": "alias" }
      ],
      [
       { "params": [ "Longitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Longitude" ], "type": "alias" }
      ],
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Battery" ], "type": "alias" }
      ],
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Humidity" ], "type": "alias" }
      ],
      [
       { "params": [ "Rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rain" ], "type": "alias" }
      ],
      [
       { "params": [ "SolarRadiation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Solar Radiation" ], "type": "alias" }
      ],
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "UV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "UV" ], "type": "alias" }
      ],
      [
       { "params": [ "WindDir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wind Direction" ], "type": "alias" }
      ],
      [
       { "params": [ "WindSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wind Speed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "Packet Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "Packet Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "PacketCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  { "title": "Wind", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "query": "SELECT \"WindDir\" FROM \"TEST\" WHERE (\"ID\"::field = '0' AND \"WindDir\"::field > 0) AND $timeFilter",
     "select": [
      [
       { "params": [ "WindDir" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "WindDir::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindDir" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "WindDir::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindDir" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "WindDir::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindDir" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "WindDir::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindDir" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "WindDir::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindDir" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "WindDir::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindDir" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "WindDir::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindDir" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "WindDir::field", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindSpeed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindSpeed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindSpeed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindSpeed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindSpeed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindSpeed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindSpeed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "WindSpeed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  { "title": "UV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "UV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "query": "SELECT \"UV\" FROM \"TEST\" WHERE (\"ID\"::field = '0' AND \"UV\"::field <= select tag value) AND $timeFilter",
     "select": [
      [
       { "params": [ "UV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "UV::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "UV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "UV::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "UV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "UV::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "UV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "UV::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "UV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "UV::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "UV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "UV::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "UV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "UV::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "UV" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "UV::field", "operator": "<=", "value": "255" }
     ]
    }
   ]
  },
  { "title": "Solar Radiation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Solar Radiation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "SolarRadiation" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "SolarRadiation::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "SolarRadiation" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "SolarRadiation::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "SolarRadiation" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "SolarRadiation::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "SolarRadiation" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "SolarRadiation::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "SolarRadiation" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "SolarRadiation::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "SolarRadiation" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "SolarRadiation::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "SolarRadiation" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "SolarRadiation::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "SolarRadiation" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "SolarRadiation::field", "operator": "<=", "value": "255" }
     ]
    }
   ]
  },
  { "title": "Rain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 69 },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "Rain::field", "operator": "<=", "value": "255" }
     ]
    }
   ]
  },
  { "title": "Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Station 0",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "Humidity::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 1",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "Humidity::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 2",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "Humidity::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 3",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "Humidity::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 4",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "Humidity::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 5",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "Humidity::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 6",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "Humidity::field", "operator": "<=", "value": "255" }
     ]
    },
    {
     "alias": "Station 7",
     "measurement": "TEST",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ID::field", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "Humidity::field", "operator": "<=", "value": "255" }
     ]
    }
   ]
  }
 ]
}